-- 1. Tabela de clientes
CREATE TABLE TB_CLIENTE (
  ID_CLIENTE NUMBER,
  DES_NOME VARCHAR2(100) NOT NULL,

  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

COMMENT ON COLUMN TB_CLIENTE.ID_CLIENTE IS 'PK';
COMMENT ON COLUMN TB_CLIENTE.DES_NOME IS 'Nome completo';


-- 2. Tabela de produtos
CREATE TABLE TB_PRODUTO (
  ID_PRODUTO NUMBER,
  DES_NOME VARCHAR2(100) NOT NULL,
  FLAG_STATUS CHAR(1) DEFAULT 'L' NOT NULL,
  NUM_VALOR NUMBER(10, 2) NOT NULL,
  NUM_QTD NUMBER DEFAULT 0 NOT NULL,

  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
  CONSTRAINT CHK_PRODUTO_STATUS CHECK (FLAG_STATUS IN ('L', 'B')),
  CONSTRAINT CHK_PRODUTO_VALOR CHECK (NUM_VALOR >= 0),
  CONSTRAINT CHK_PRODUTO_QTD CHECK (NUM_QTD >= 0)
);

COMMENT ON COLUMN TB_PRODUTO.ID_PRODUTO IS 'PK';
COMMENT ON COLUMN TB_PRODUTO.DES_NOME IS 'Nome';
COMMENT ON COLUMN TB_PRODUTO.FLAG_STATUS IS 'Situação: [L]iberado, [B]loqueado';
COMMENT ON COLUMN TB_PRODUTO.NUM_VALOR IS 'Preço unitário';
COMMENT ON COLUMN TB_PRODUTO.NUM_QTD IS 'Quantidade em estoque';


-- 3. Tabela de movimentações de produtos
CREATE TABLE TB_MOV_PRODUTO (
  ID_MOV_PRODUTO NUMBER,
  ID_PRODUTO NUMBER NOT NULL,
  FLAG_TIPO CHAR(1) NOT NULL,
  NUM_QTD NUMBER NOT NULL,
  NUM_VALOR_UNITARIO NUMBER(10, 2) NOT NULL,

  CONSTRAINT PK_MOV_PRODUTO PRIMARY KEY (ID_MOV_PRODUTO),
  CONSTRAINT FK_MOV_PRODUTO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
  CONSTRAINT CHK_MOV_PRODUTO_TIPO CHECK (FLAG_TIPO IN ('E', 'S')),
  CONSTRAINT CHK_MOV_PRODUTO_QTD CHECK (NUM_QTD > 0),
  CONSTRAINT CHK_MOV_PRODUTO_VALOR_UNITARIO CHECK (NUM_VALOR_UNITARIO >= 0)
);

COMMENT ON COLUMN TB_MOV_PRODUTO.ID_MOV_PRODUTO IS 'PK';
COMMENT ON COLUMN TB_MOV_PRODUTO.ID_PRODUTO IS 'FK - Produto';
COMMENT ON COLUMN TB_MOV_PRODUTO.FLAG_TIPO IS 'Tipo: [E]ntrada, [S]aída';
COMMENT ON COLUMN TB_MOV_PRODUTO.NUM_QTD IS 'Quantidade de produtos';
COMMENT ON COLUMN TB_MOV_PRODUTO.NUM_VALOR_UNITARIO IS 'Valor unitário do produto';


-- 4. Tabela de pedidos
CREATE TABLE TB_PEDIDO (
  ID_PEDIDO NUMBER,
  ID_CLIENTE NUMBER NOT NULL,
  NUM_VALOR_TOTAL NUMBER(10, 2) NOT NULL,
  FLAG_STATUS CHAR(1) DEFAULT 'P' NOT NULL,

  CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
  CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
  CONSTRAINT CHK_PEDIDO_VALOR_TOTAL CHECK (NUM_VALOR_TOTAL >= 0),
  CONSTRAINT CHK_PEDIDO_STATUS CHECK (FLAG_STATUS IN ('E', 'C', 'P'))
);

COMMENT ON COLUMN TB_PEDIDO.ID_PEDIDO IS 'PK';
COMMENT ON COLUMN TB_PEDIDO.ID_CLIENTE IS 'FK - Cliente';
COMMENT ON COLUMN TB_PEDIDO.NUM_VALOR_TOTAL IS 'Valor total';
COMMENT ON COLUMN TB_PEDIDO.FLAG_STATUS IS 'Situação: [E]fetivado, [C]ancelado, [P]endente';


-- 5. Tabela de movimentações de pedidos
CREATE TABLE TB_MOV_PEDIDO (
  ID_PEDIDO NUMBER NOT NULL,
  ID_PRODUTO NUMBER NOT NULL,
  NUM_QTD_PRODUTO NUMBER NOT NULL,
  NUM_VALOR_UNITARIO NUMBER(10, 2) NOT NULL,

  CONSTRAINT FK_MOV_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO),
  CONSTRAINT FK_MOV_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
  CONSTRAINT CHK_MOV_PEDIDO_QTD_PRODUTO CHECK (NUM_QTD_PRODUTO > 0),
  CONSTRAINT CHK_MOV_PEDIDO_VALOR_UNITARIO CHECK (NUM_VALOR_UNITARIO >= 0)
);

COMMENT ON COLUMN TB_MOV_PEDIDO.ID_PEDIDO IS 'FK - Pedido';
COMMENT ON COLUMN TB_MOV_PEDIDO.ID_PRODUTO IS 'FK - Produto';
COMMENT ON COLUMN TB_MOV_PEDIDO.NUM_QTD_PRODUTO IS 'Quantidade do produto movimentado';
COMMENT ON COLUMN TB_MOV_PEDIDO.NUM_VALOR_UNITARIO IS 'Valor unitário do produto';
