-- Limpeza de objetos

DROP PACKAGE PKG_PEDIDO;

DROP TABLE TB_MOV_PRODUTO;
DROP TABLE TB_MOV_PEDIDO;
DROP TABLE TB_PEDIDO;
DROP TABLE TB_PRODUTO;
DROP TABLE TB_CLIENTE;

DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_PRODUTO;
DROP SEQUENCE SEQ_MOV_PRODUTO;
DROP SEQUENCE SEQ_PEDIDO;
