-- Limpeza de dados

DELETE FROM TB_MOV_PRODUTO WHERE 1 = 1;
DELETE FROM TB_MOV_PEDIDO WHERE 1 = 1;
DELETE FROM TB_PEDIDO WHERE 1 = 1;
DELETE FROM TB_PRODUTO WHERE 1 = 1;
DELETE FROM TB_CLIENTE WHERE 1 = 1;

DECLARE
  V_CURRVAL NUMBER;
BEGIN
  SELECT SEQ_CLIENTE.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_CLIENTE INCREMENT BY -' || V_CURRVAL || ' MINVALUE 0';
  SELECT SEQ_CLIENTE.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_CLIENTE INCREMENT BY 1';
END;
/

DECLARE
  V_CURRVAL NUMBER;
BEGIN
  SELECT SEQ_PRODUTO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PRODUTO INCREMENT BY -' || V_CURRVAL || ' MINVALUE 0';
  SELECT SEQ_PRODUTO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PRODUTO INCREMENT BY 1';
END;
/

DECLARE
  V_CURRVAL NUMBER;
BEGIN
  SELECT SEQ_MOV_PRODUTO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_MOV_PRODUTO INCREMENT BY -' || V_CURRVAL || ' MINVALUE 0';
  SELECT SEQ_MOV_PRODUTO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_MOV_PRODUTO INCREMENT BY 1';
END;
/

DECLARE
  V_CURRVAL NUMBER;
BEGIN
  SELECT SEQ_PEDIDO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PEDIDO INCREMENT BY -' || V_CURRVAL || ' MINVALUE 0';
  SELECT SEQ_PEDIDO.NEXTVAL INTO V_CURRVAL FROM DUAL;
  EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PEDIDO INCREMENT BY 1';
END;
/
